spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1908
    driver-class-name: org.postgresql.Driver

  flyway:
    baselineOnMigrate: true
    location: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081