spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8082

service:
  emulate-services:
    url: "localhost:8091"
    endpoint: "/api"

logging:
  file:
    name: ./sms-blacklist/logs/sms-blacklist.log
    max-size: 200 KB
  pattern:
    rolling-file-name: ./sms-blacklist/logs/sms-blacklist-%d{yyyy-MM-dd}.%i.log
    file: "%d{yyyy-mm-dd  HH:mm:ss.SSS} [%thread] -- %-5level -- %logger{36} - [%file:%line] : %msg%n"
    console: "%d{yyyy-mm-dd  HH:mm:ss.SSS} [%thread] -- %-5level -- %logger{36} - [%file:%line] : %msg{magenta}%n"
  level:
    ru.oksk.study.sms.server: INFO
    org.springframework: WARN